In [23]:
import numpy as np
from math import cos,sin,pi

In [25]:
def calculate_fixed_point(fix_point,R,position):
    k1=(fix_point[3]-fix_point[1])/(fix_point[2]-fix_point[0])#k1=(y2-y1)/(x2-x1)
    k2=(fix_point[7]-fix_point[5])/(fix_point[6]-fix_point[4])#k2=(y4-y3)/(x4-x3)
    k11=-1/k1#垂直平分线1的斜率
    k22=-1/k2#垂直平分线2的斜率
    x01=(fix_point[0]+fix_point[2])/2#x01=(x1+x2)/2——中点1的横坐标
    y01=(fix_point[1]+fix_point[3])/2#y01=(y1+y2)/2——中点1的纵坐标
    x02=(fix_point[4]+fix_point[6])/2#x02=(x3+x4)/2——中点2的横坐标
    y02=(fix_point[5]+fix_point[7])/2#y02=(y3+y4)/2——中点2的纵坐标
    x=((k11*x01-y01)-(k22*x02-y02))/(k11-k22)
    y=k11*(x-x01)+y01#(x,y)为圆心O'的坐标
    r2=(x-fix_point[0])**2+(y-fix_point[1])**2
    #得到圆心的x,y坐标后还需要求解z坐标
    distance=(R**2-r2)**0.5#z方向的垂直距离
    if position==1:
        z=-distance
    else:
        z=distance
    circle_point=np.array([x,y,z]).reshape(-1,1)
    I=np.eye(3)
    h_stack=np.hstack((I,circle_point))
    one=np.array([0,0,0,1])
    TC=np.vstack((h_stack,one))
    return TC

In [26]:
def axis_transformtion(x):
    result=[]
    for i in [0,2,4,6]:
        x0=x[i]*cos(x[i+1]/180*pi)
        y0=x[i]*sin(x[i+1]/180*pi)
        result.append(x0)
        result.append(y0)
    return result

In [27]:
fix_point1=list(map(float,input("请输入位姿1下点云数据中的4个点:").split()))
fix_point1=axis_transformtion(fix_point1)
print(fix_point1)
R=246
TC1=calculate_fixed_point(fix_point1,R,position=1)
print(TC1)

[2.9926921507794724, 0.2092694212323759, 4.972609476841367, 0.5226423163382673, 6.931876481190993, 0.9742117067204581, 7.878462024097664, 1.3891854213354426]
[[   1.            0.            0.            1.84672582]
 [   0.            1.            0.           13.86091657]
 [   0.            0.            1.         -245.61823892]
 [   0.            0.            0.            1.        ]]
